//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TQMallAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewProduct
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public int IDProduct { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Review { get; set; }
        public string Image { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
    }
}
